- hosts: localhost
  become: yes
  tasks:
    - name: Install Dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - podman
        state: present

    - name: Add Kubernetes signing key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes Repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Update package lists
      apt:
        update_cache: yes
    
    - name: Install Kubernetes Packages
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present

    - name: Hold Kubernetes Packages to prevent automatic updates
      dpkg_selections:
        name: "{{ item }}"
        selection: hold

      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started


